apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: default
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/loki/charts
    targetRevision: 2.1.0
    chart: loki-stack
    helm:
      valueFiles:
      - values.yaml
      values: |-
        loki:
          nodeSelector:
            kubernetes.io/arch: arm64
          persistence:
            enabled: false
