apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-external
  namespace: argocd
spec:
  destination:
    namespace: ingress-external
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.15
    chart: ingress-nginx
    helm:
      valueFiles:
      - values.yaml
      values: |-
        controller:
          admissionWebhooks:
            enabled: false
          hostport:
            enabled: true
          ingressClassResource:
            name: external
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/ingress-external: ""
          tolerations:
          - effect: NoSchedule
            key: ingress-external
            operator: "Equal"
            value: "true"
          replicaCount: 2
          service:
            enabled: false
          publishService:
            enabled: false
          metrics:
            enabled: true
          serviceMonitor:
            enabled: true
          config:
            use-proxy-protocol: "true"
            use-forwarded-headers: "true"
# podAntiAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#   - labelSelector:
#       matchExpressions:
#       - key: app.kubernetes.io/name
#         operator: In
#         values:
#         - ingress-nginx-internal
#     topologyKey: "kubernetes.io/hostname"
