ingress-nginx:
  controller:
    admissionWebhooks:
      enabled: false
    hostport:
      enabled: true
    ingressClassResource:
      name: external
    ingressClass: external
    updateStrategy:
      type: Recreate
    hostNetwork: false
    nodeSelector:
      node-role.kubernetes.io/ingress-external: ""
    tolerations:
    - effect: NoSchedule
      key: ingress-external
      operator: "Equal"
      value: "true"
    replicaCount: 1
    service:
      enabled: false
    publishService:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      use-proxy-protocol: "true"
      use-forwarded-headers: "true"
