apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slackurl
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: slackurl
    remoteRef:
      key: slackurl
      property: password
