{{- if eq .Values.env "internal" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt-staging
spec:
  acme:
    email: igou.david@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: dns-token
            name: dns-token
          email: igou.david@gmail.com
      selector:
        dnsZones:
          - igou.systems
{{- end }}
{{- if eq .Values.env "external" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt-staging
spec:
  acme:
    email: igou.david@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: dns-token
            name: dns-token
          email: igou.david@gmail.com
      selector:
        dnsZones:
          - igou.io
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: cbull-dns-token
            name: cbull-dns-token
          email: bullcs95@gmail.com
      selector:
        dnsZones:
          - cbull.dev
    - http01:
        ingress: {}
{{- end }}
