apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app.kubernetes.io/name: prometheus
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
     targetPortal: 10.10.1.5:3260
     iqn: iqn.2023-04.systems.igou.dmz:prometheus
     lun: 0
     fsType: 'ext4'
