apiVersion: v1
kind: Secret
metadata:
  name: virtualmachine-deployer-token
  namespace: kubevirt
  annotations:
    kubernetes.io/service-account.name: virtualmachine-deployer
type: kubernetes.io/service-account-token