apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtualmachine-reader
subjects:
- kind: ServiceAccount
  name: virtualmachine-reader
  namespace: kubevirt
roleRef:
  kind: ClusterRole
  name: virtualmachine-reader
  apiGroup: rbac.authorization.k8s.io