apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-security-group
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync-security-group
              image: amazon/aws-cli:latest
              command: ["sh", "/scripts/sync-security-group.sh"]
              resources:
                requests:
                  cpu: "50m"
                  memory: "50Mi"
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws_secret_access_key
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: settings
                  mountPath: /settings
                - name: scripts
                  mountPath: /scripts
                - name: aws-credentials
                  mountPath: /root/.aws
          volumes:
            - name: config
              configMap:
                name: allowed-ips
                items:
                  - key: ip-addresses.txt
                    path: ip-addresses.txt
            - name: settings
              configMap:
                name: security-group-settings
            - name: scripts
              configMap:
                name: sync-security-group-script
            - name: aws-credentials
              secret:
                secretName: aws-credentials
          restartPolicy: OnFailure
