loki:
  minio:
    enabled: true
    persistence:
      enabled: false 
  test:
    enabled: false
  read:
    replicas: 1
  write:
    replicas: 1
  monitoring:
    dashboards:
      enabled: false
    serviceMonitor:
      enabled: false
    metricsInstance:
      enabled: false
  persistence:
    enabled: false
promtail:
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
  tolerations:
    - effect: NoSchedule
      operator: Exists
