loki-stack:
  loki:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
    persistence:
      enabled: false
  promtail:
    config:
      lokiAddress: http://logging-loki.logging:3100/loki/api/v1/push
    tolerations:
      - effect: NoSchedule
        operator: Exists
