---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keepalived-operator
subjects:
- kind: ServiceAccount
  name: keepalived-operator
roleRef:
  kind: Role
  name: keepalived-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keepalived-operator
subjects:
- kind: ServiceAccount
  name: keepalived-operator
  namespace: keepalived-operator 
roleRef:
  kind: ClusterRole
  name: keepalived-operator
  apiGroup: rbac.authorization.k8s.io
