apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.38.2/release.yaml
  - https://github.com/tektoncd/dashboard/releases/download/v0.28.0/tekton-dashboard-release.yaml
patches:
 - target:
     kind: StatefulSet
   patch: |-
     apiVersion: apps/v1
     kind: StatefulSet
     metadata:
       name: deploy
     spec:
       template:
         spec:
           nodeSelector:
             node-role.kubernetes.io/infra: ""
           tolerations:
           - effect: NoSchedule
             key: node-role.kubernetes.io/infra
             value: reserved
           - effect: NoExecute
             key: node-role.kubernetes.io/infra
             value: reserved
 - target:
     kind: Deployment
   patch: |-
     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: deploy
     spec:
       template:
         spec:
           nodeSelector:
             node-role.kubernetes.io/infra: ""
           tolerations:
           - effect: NoSchedule
             key: node-role.kubernetes.io/infra
             value: reserved
           - effect: NoExecute
             key: node-role.kubernetes.io/infra
             value: reserved
