apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/dashboard/latest/tekton-dashboard-release.yaml
  - tekton-dashboard-ingress.yaml
patches:
 - target:
     kind: StatefulSet
   patch: |-
     apiVersion: apps/v1
     kind: StatefulSet
     metadata:
       name: deploy
     spec:
       template:
         spec:
           nodeSelector:
             node-role.kubernetes.io/infra: ""
           tolerations:
           - effect: NoSchedule
             key: node-role.kubernetes.io/infra
             value: reserved
           - effect: NoExecute
             key: node-role.kubernetes.io/infra
             value: reserved
 - target:
     kind: Deployment
   patch: |-
     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: deploy
     spec:
       template:
         spec:
           nodeSelector:
             node-role.kubernetes.io/infra: ""
           tolerations:
           - effect: NoSchedule
             key: node-role.kubernetes.io/infra
             value: reserved
           - effect: NoExecute
             key: node-role.kubernetes.io/infra
             value: reserved
