configExternalSecret:
  name: &configExternalSecret "truenas-csi-nuc7-nfs"
democratic-csi:
  csiDriver:
    name: "org.democratic-csi.nfs"
    fsGroupPolicy: File
  storageClasses:
    - name: freenas-nfs-csi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
      mountOptions:
        - noatime
        - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
  volumeSnapshotClasses: []
  driver:
    existingConfigSecret: *configExternalSecret
    config:
      driver: freenas-nfs