apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argo-cert
  namespace: default
spec:
  commonName: argo.igou.io
  dnsNames:
  - argo.igou.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: argo-acme-certificate
