apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "https://github.com/argoproj/argo-rollouts.git/manifests/cluster-install/?ref=v1.3.2"
namespace: argo-rollouts
commonAnnotations:
  env: igoucorp
patches:
 - target:
     kind: Deployment
   patch: |-
     apiVersion: apps/v1
     kind: Deployment
     metadata:
       name: deploy
     spec:
       template:
         spec:
           nodeSelector:
             node-role.kubernetes.io/infra: ""
           tolerations:
           - effect: NoSchedule
             key: node-role.kubernetes.io/infra
             value: reserved
           - effect: NoExecute
             key: node-role.kubernetes.io/infra
             value: reserved
