apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dns-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
  - secretKey: dns-token
    remoteRef:
      key: dns-token
      property: password
