apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  name: letsencrypt-staging
spec:
  acme:
    email: igou.david@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: example-issuer-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress: {}
      selector: {}
