apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  data:
    - secretKey: rcon-password
      remoteRef:
        key: minecraft-secrets
        property: rcon-password
    - secretKey: rclone.conf
      remoteRef:
        key: minecraft-secrets
        property: rclone.conf
