apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sync-security-group-cronjob.yml
configMapGenerator:
- name: sync-security-group-script
  files:
  - sync-security-group.sh
