apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-security-group
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sync-security-group
              image: amazon/aws-cli:latest
              command: ["sh", "/scripts/sync-security-group.sh"]
              resources:
                requests:
                  cpu: "50m"
                  memory: "50Mi"
              volumeMounts:
                - name: ip-addresses
                  mountPath: /config/allowed-ips
                  subPath: ip-addresses.txt
                - name: settings
                  mountPath: /settings/port
                  subPath: port
                - name: settings
                  mountPath: /settings/protocol
                  subPath: protocol
                - name: settings
                  mountPath: /settings/group-id
                  subPath: group-id
                - name: settings
                  mountPath: /settings/aws-region
                  subPath: aws-region
                - name: scripts
                  mountPath: /scripts
                - name: aws-credentials
                  mountPath: /root/.aws
          volumes:
            - name: ip-addresses
              configMap:
                name: ip-addresses
            - name: settings
              configMap:
                name: security-group-settings
            - name: scripts
              configMap:
                name: sync-security-group-script
            - name: aws-credentials
              secret:
                secretName: aws-credentials
          restartPolicy: OnFailure
