apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "truenas-csi-nuc7-nfs"
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
  - extract:
      key: "truenas-csi-nuc7-nfs"