app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        - 65536
  controllers:
    main:
      containers:
        main:
          nameOverride: qbittorrent
          env:
            UMASK: "022"
          image:
            repository: ghcr.io/onedr0p/qbittorrent
            tag: 4.6.2
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
          securityContext:
            runAsUser: 568
            runAsGroup: 568
  service:
    main:
      ports:
        http:
          port: 8080
  ingress:
    main:
      enabled: true
      className: nginx
      hosts:
        - host: &host qb.apps.igou.systems
          paths:
            - path: /
              service:
                name: main
                port: http
  persistence:
    media:
      type: persistentVolumeClaim
      enabled: true
      accessMode: ReadWriteOnce
      retain: true
      size: 500Gi
      storageClass: nfs-client
      advancedMounts:
        main:
          main:
            - path: /downloads
    config:
      type: persistentVolumeClaim
      enabled: true
      accessMode: ReadWriteOnce
      retain: true
      size: 1Gi
      storageClass: nfs-client
      advancedMounts:
        main:
          main:
            - path: /config
  networkpolicies:
    main:
      enabled: true
      controller: main
      policyTypes:
        - Ingress
        - Egress
      rules:
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: ingress
                podSelector:
                  matchLabels:
                    app.kubernetes.io/name: nginx
        egress:
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: kube-system
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
            ports:
              port: 53
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                    - 10.0.0.0/8
                    - 172.16.0.0/12
                    - 192.168.0.0/16
            ports:
              protocol: UDP
              port: 51820