apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slackurl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
  - secretKey: slackurl
    remoteRef:
      key: slackurl
      property: password
