kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-to-kube-dns
spec:
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
