apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
  - secretKey: cookie-secret
    remoteRef:
      key: oauth2-proxy-secrets
      property: cookiesecret
  - secretKey: client-secret
    remoteRef:
      key: oauth2-proxy-secrets
      property: clientsecret
  - secretKey: client-id
    remoteRef:
      key: oauth2-proxy-secrets
      property: clientid
