apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stackrox-db
  namespace: stackrox
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#  storageClassName: local-path-immediate
  volumeMode: Filesystem
