loki:
  loki:
    commonConfig:
      replication_factor: 2
    storage:
      type: 's3'
      bucketNames:
        chunks: loki
        ruler: loki
        admin: loki
      s3:
        s3: null
        s3ForcePathStyle: true
        insecure: true
        endpoint: http://minio.minio.svc.cluster.local:9000
        accessKeyId: loki-svcacct
        secretAccessKey: ${S3_LOKI_SECRET_ACCESS_KEY}
  singleBinary:
    replicas: 2
    extraArgs:
      - '-config.expand-env=true'
    extraEnv:
      - name: S3_LOKI_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: loki-bucket-secret
            key: loki-bucket-secret

promtail:
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://logging-loki.logging:3100/loki/api/v1/push
