apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-bucket-secret
  namespace: logging
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  data:
    - secretKey: loki-bucket-secret
      remoteRef:
        key: minio-user-secret-keys
        property: loki-svcacct-secret-key
