apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chap-secret
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    template:
      type: kubernetes.io/iscsi-chap
  data:
    - secretKey: node.session.auth.username
      remoteRef:
        key: awx-postgres-iscsi-chap
        property: username
    - secretKey: node.session.auth.password
      remoteRef:
        key: awx-postgres-iscsi-chap
        property: password
