apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-iscsi-pv
  labels:
    app.kubernetes.io/name: prometheus
spec:
  storageClassName: "awx-postgres"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.2.5:3260
    iqn: iqn.2000-01.com.synology:igounas.awx-postgres.220186445f7
    lun: 1
    fsType: ext4
    readOnly: false
    secretRef:
      name: chap-secret
      namespace: monitoring
    chapAuthDiscovery: true
    chapAuthSession: true
