ingress-nginx:
  controller:
    kind: DaemonSet
    admissionWebhooks:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      use-proxy-protocol: "true"
      use-forwarded-headers: "true"
