ingress-nginx:
  controller:
    kind: DaemonSet
    service:
      annotations:
        tailscale.com/expose: "true"
      type: "NodePort"
      nodePorts:
        https: 30443
    admissionWebhooks:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      use-proxy-protocol: "true"
      use-forwarded-headers: "true"
