ingress-nginx:
  controller:
    admissionWebhooks:
      enabled: false
    hostport:
      enabled: true
    kind: DaemonSet
    hostNetwork: false
    nodeSelector:
      node-role.kubernetes.io/worker: "true"
    service:
      enabled: false
    publishService:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
