apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mullvad
  namespace: vpn
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: mullvad
      property: wireguard-key
    secretKey: WIREGUARD_PRIVATE_KEY
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: mullvad
      property: wireguard-ip-address
    secretKey: WIREGUARD_ADDRESSES
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
